name: Noah Guzman
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
#theme: jekyll-theme-minimal
remote_theme: minimal-mistakes-jekyll
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
