name: Noah Guzmán
author:
  name: Noah Guzmán
  email: nguzman@caltech.edu
  social:
    email: nguzman@caltech.edu
    github:  nguzman313
    twitter: NoahGuzman14

markdown: kramdown
permalink: /blog/:year/:month/:day/:title
#theme: jekyll-theme-minimal
#remote_theme: mmistakes/minimal-mistakes
remote_theme: hydecorp/hydejack@v9.0.4
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme
menu:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
paginate:      10
paginate_path: /blog/:num/ #!!
accent_image: none
accent_color: rgb(53,56,54)
sidebar_title: Noah Guzmán
short_title: Noah Guzmán
title: Noah Guzmán
logo: /assets/your-image@0,25x.jpg
#  srcset:
#    1920w: /assets/your-image.jpg
#    960w: /assets/your-image@0,5x.jpg
#    480w: /assets/your-image@0,25x.jpg

