name: Noah Guzmán
author: Noah Guzmán
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
#theme: jekyll-theme-minimal
#remote_theme: mmistakes/minimal-mistakes
remote_theme: hydecorp/hydejack@v9.0.4
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme
menu:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
paginate:      10
paginate_path: /blog/:num/ #!!
